# Generated by Django 3.0.3 on 2020-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='comentarios',
            new_name='review',
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
