# Generated by Django 3.0.3 on 2020-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0002_auto_20200329_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(help_text='Preparacion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.TextField(help_text='Minutos para realizar la receta'),
        ),
    ]
