# Generated by Django 3.0.3 on 2020-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0003_auto_20200329_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(help_text='Minutos para realizar la receta'),
        ),
    ]
