# Generated by Django 3.0.3 on 2020-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0004_auto_20200329_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(help_text='Preparación y pasos a seguir'),
        ),
    ]
