# Generated by Django 3.0.3 on 2020-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0005_auto_20200329_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(default=60, help_text='Minutos para realizar la receta'),
        ),
    ]
