# Generated by Django 3.0.3 on 2020-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0006_auto_20200329_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='review',
            field=models.CharField(blank=True, help_text='Espacio para comentarios', max_length=1000, null=True),
        ),
    ]
