# Generated by Django 3.0.3 on 2020-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0007_auto_20200329_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='recetaprivada',
            field=models.BooleanField(default=False),
        ),
    ]
