# Generated by Django 3.0.3 on 2020-03-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAndFun', '0008_receta_recetaprivada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='recetaprivada',
            new_name='receta_privada',
        ),
    ]
